import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';

export type DemoLanguage = 'es' | 'en';

export const useDemoLanguage = () => {
  const [searchParams] = useSearchParams();
  const [language, setLanguage] = useState<DemoLanguage>('es');

  useEffect(() => {
    const langParam = searchParams.get('lang') as DemoLanguage;
    if (langParam && (langParam === 'es' || langParam === 'en')) {
      setLanguage(langParam);
    }
  }, [searchParams]);

  return { language, setLanguage };
};

// Textos traducidos
export const demoTexts = {
  es: {
    welcome: "Bienvenido a tu Liga",
    welcomeSubtitle: "Gestiona tu liga de apuestas deportivas",
    weeklyBudget: "Presupuesto Semanal",
    totalPoints: "Puntos Totales",
    thisWeek: "Esta Semana",
    lastWeek: "Semana Pasada",
    quickActions: "Acciones Rápidas",
    placeBets: "Hacer Apuestas",
    viewHistory: "Ver Historial",
    viewStandings: "Ver Clasificación",
    demoMode: "Modo Demo",
    demoDescription: "Esta es una demostración de la aplicación. Los datos mostrados son ficticios.",
    bets: "Apuestas",
    betHistory: "Historial de Apuestas",
    standings: "Clasificación",
    settings: "Configuración",
    logout: "Cerrar Sesión",
    home: "Inicio",
    profile: "Perfil",
    admin: "Administración",
    league: "Liga",
    matches: "Partidos",
    odds: "Cuotas",
    stake: "Cantidad",
    placeBet: "Hacer Apuesta",
    clearBet: "Limpiar Apuesta",
    totalStake: "Cantidad Total",
    potentialWin: "Ganancia Potencial",
    minBet: "Apuesta Mínima",
    maxBet: "Apuesta Máxima",
    balance: "Saldo",
    week: "Semana",
    season: "Temporada",
    position: "Posición",
    player: "Jugador",
    points: "Puntos",
    wins: "Victorias",
    losses: "Derrotas",
    winRate: "% Victorias",
    totalBets: "Total Apuestas",
    wonBets: "Apuestas Ganadas",
    lostBets: "Apuestas Perdidas",
    pendingBets: "Apuestas Pendientes",
    totalWagered: "Total Apostado",
    totalWon: "Total Ganado",
    profit: "Beneficio",
    roi: "ROI",
    filterBy: "Filtrar por",
    all: "Todas",
    won: "Ganadas",
    lost: "Perdidas",
    pending: "Pendientes",
    cancelled: "Canceladas",
    noBets: "No tienes apuestas todavía",
    noWonBets: "No tienes apuestas ganadas todavía",
    noLostBets: "No tienes apuestas perdidas todavía",
    noPendingBets: "No tienes apuestas pendientes todavía",
    noCancelledBets: "No tienes apuestas canceladas todavía",
    upcomingMatches: "Próximos encuentros",
    oddsAvailableSoon: "Las apuestas para este partido estarán disponibles próximamente",
    noMarketsAvailable: "No hay mercados de apuestas disponibles para este partido",
    liveBetting: "Apuestas en Vivo",
    liveBettingDescription: "Apuestas disponibles durante el partido",
    preMatch: "Pre-Partido",
    preMatchDescription: "Apuestas disponibles antes del inicio del partido",
    result: "Resultado",
    totalGoals: "Total Goles",
    bothTeamsScore: "Ambos Equipos Marcan",
    correctScore: "Resultado Exacto",
    halftimeFulltime: "Medio Tiempo / Final",
    overUnder: "Más/Menos",
    winner: "Ganador",
    exactScore: "Resultado Exacto",
    halftimeResult: "Resultado Medio Tiempo",
    fulltimeResult: "Resultado Final",
    totalGoalsOverUnder: "Total Goles Más/Menos",
    bothTeamsToScore: "Ambos Equipos Marcan",
    homeTeam: "Equipo Local",
    awayTeam: "Equipo Visitante",
    draw: "Empate",
    over: "Más",
    under: "Menos",
    yes: "Sí",
    no: "No",
    select: "Seleccionar",
    selected: "Seleccionado",
    clear: "Limpiar",
    confirm: "Confirmar",
    cancel: "Cancelar",
    save: "Guardar",
    edit: "Editar",
    delete: "Eliminar",
    back: "Volver",
    next: "Siguiente",
    previous: "Anterior",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    warning: "Advertencia",
    info: "Información",
    search: "Buscar",
    filter: "Filtrar",
    sort: "Ordenar",
    refresh: "Actualizar",
    copy: "Copiar",
    share: "Compartir",
    print: "Imprimir",
    download: "Descargar",
    upload: "Subir",
    close: "Cerrar",
    open: "Abrir",
    show: "Mostrar",
    hide: "Ocultar",
    expand: "Expandir",
    collapse: "Contraer",
    more: "Más",
    less: "Menos",
    none: "Ninguno",
    selectAll: "Seleccionar Todo",
    deselectAll: "Deseleccionar Todo",
    reset: "Resetear",
    apply: "Aplicar",
    submit: "Enviar",
    continue: "Continuar",
    finish: "Finalizar",
    start: "Iniciar",
    stop: "Detener",
    pause: "Pausar",
    resume: "Reanudar",
    retry: "Reintentar",
    skip: "Omitir",
    done: "Hecho",
    complete: "Completado",
    incomplete: "Incompleto",
    active: "Activo",
    inactive: "Inactivo",
    enabled: "Habilitado",
    disabled: "Deshabilitado",
    visible: "Visible",
    hidden: "Oculto",
    public: "Público",
    private: "Privado",
    draft: "Borrador",
    published: "Publicado",
    archived: "Archivado",
    deleted: "Eliminado",
    created: "Creado",
    updated: "Actualizado",
    modified: "Modificado",
    lastModified: "Última Modificación",
    createdAt: "Creado en",
    updatedAt: "Actualizado en",
    expiresAt: "Expira en",
    startsAt: "Inicia en",
    endsAt: "Termina en",
    duration: "Duración",
    timeRemaining: "Tiempo Restante",
    timeElapsed: "Tiempo Transcurrido",
    totalTime: "Tiempo Total",
    averageTime: "Tiempo Promedio",
    fastestTime: "Tiempo Más Rápido",
    slowestTime: "Tiempo Más Lento",
    bestTime: "Mejor Tiempo",
    worstTime: "Peor Tiempo",
    personalBest: "Mejor Personal",
    worldRecord: "Récord Mundial",
    leagueRecord: "Récord de Liga",
    seasonRecord: "Récord de Temporada",
    weekRecord: "Récord de Semana",
    dayRecord: "Récord del Día",
    hourRecord: "Récord de la Hora",
    minuteRecord: "Récord del Minuto",
    secondRecord: "Récord del Segundo",
    millisecondRecord: "Récord del Milisegundo"
  },
  en: {
    welcome: "Welcome to your League",
    welcomeSubtitle: "Manage your sports betting league",
    weeklyBudget: "Weekly Budget",
    totalPoints: "Total Points",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    quickActions: "Quick Actions",
    placeBets: "Place Bets",
    viewHistory: "View History",
    viewStandings: "View Standings",
    demoMode: "Demo Mode",
    demoDescription: "This is a demonstration of the application. The data shown is fictional.",
    bets: "Bets",
    betHistory: "Bet History",
    standings: "Standings",
    settings: "Settings",
    logout: "Logout",
    home: "Home",
    profile: "Profile",
    admin: "Administration",
    league: "League",
    matches: "Matches",
    odds: "Odds",
    stake: "Stake",
    placeBet: "Place Bet",
    clearBet: "Clear Bet",
    totalStake: "Total Stake",
    potentialWin: "Potential Win",
    minBet: "Minimum Bet",
    maxBet: "Maximum Bet",
    balance: "Balance",
    week: "Week",
    season: "Season",
    position: "Position",
    player: "Player",
    points: "Points",
    wins: "Wins",
    losses: "Losses",
    winRate: "Win Rate",
    totalBets: "Total Bets",
    wonBets: "Won Bets",
    lostBets: "Lost Bets",
    pendingBets: "Pending Bets",
    totalWagered: "Total Wagered",
    totalWon: "Total Won",
    profit: "Profit",
    roi: "ROI",
    filterBy: "Filter by",
    won: "Won",
    lost: "Lost",
    pending: "Pending",
    cancelled: "Cancelled",
    noBets: "You don't have any bets yet",
    noWonBets: "You don't have any won bets yet",
    noLostBets: "You don't have any lost bets yet",
    noPendingBets: "You don't have any pending bets yet",
    noCancelledBets: "You don't have any cancelled bets yet",
    upcomingMatches: "Upcoming matches",
    oddsAvailableSoon: "Bets for this match will be available soon",
    noMarketsAvailable: "No betting markets available for this match",
    liveBetting: "Live Betting",
    liveBettingDescription: "Bets available during the match",
    preMatch: "Pre-Match",
    preMatchDescription: "Bets available before match start",
    result: "Result",
    totalGoals: "Total Goals",
    bothTeamsScore: "Both Teams Score",
    correctScore: "Correct Score",
    halftimeFulltime: "Half Time / Full Time",
    overUnder: "Over/Under",
    winner: "Winner",
    exactScore: "Exact Score",
    halftimeResult: "Half Time Result",
    fulltimeResult: "Full Time Result",
    totalGoalsOverUnder: "Total Goals Over/Under",
    bothTeamsToScore: "Both Teams to Score",
    homeTeam: "Home Team",
    awayTeam: "Away Team",
    draw: "Draw",
    over: "Over",
    under: "Under",
    yes: "Yes",
    no: "No",
    select: "Select",
    selected: "Selected",
    clear: "Clear",
    confirm: "Confirm",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    back: "Back",
    next: "Next",
    previous: "Previous",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    refresh: "Refresh",
    copy: "Copy",
    share: "Share",
    print: "Print",
    download: "Download",
    upload: "Upload",
    close: "Close",
    open: "Open",
    show: "Show",
    hide: "Hide",
    expand: "Expand",
    collapse: "Collapse",
    reset: "Reset",
    apply: "Apply",
    submit: "Submit",
    continue: "Continue",
    finish: "Finish",
    start: "Start",
    stop: "Stop",
    pause: "Pause",
    resume: "Resume",
    retry: "Retry",
    skip: "Skip",
    done: "Done",
    complete: "Complete",
    incomplete: "Incomplete",
    active: "Active",
    inactive: "Inactive",
    enabled: "Enabled",
    disabled: "Disabled",
    visible: "Visible",
    hidden: "Hidden",
    public: "Public",
    private: "Private",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    deleted: "Deleted",
    created: "Created",
    updated: "Updated",
    modified: "Modified",
    lastModified: "Last Modified",
    createdAt: "Created At",
    updatedAt: "Updated At",
    expiresAt: "Expires At",
    startsAt: "Starts At",
    endsAt: "Ends At",
    duration: "Duration",
    timeRemaining: "Time Remaining",
    timeElapsed: "Time Elapsed",
    totalTime: "Total Time",
    averageTime: "Average Time",
    fastestTime: "Fastest Time",
    slowestTime: "Slowest Time",
    bestTime: "Best Time",
    worstTime: "Worst Time",
    personalBest: "Personal Best",
    worldRecord: "World Record",
    leagueRecord: "League Record",
    seasonRecord: "Season Record",
    weekRecord: "Week Record",
    dayRecord: "Day Record",
    hourRecord: "Hour Record",
    minuteRecord: "Minute Record",
    secondRecord: "Second Record",
    millisecondRecord: "Millisecond Record"
  }
};
