// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqxpfllddhxjjfmdbpqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxeHBmbGxkZGh4ampmbWRicHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDYyNjksImV4cCI6MjA3MDk4MjI2OX0.Jk3p1NM3r7nOi72ma81TcY7d5UIHs-EHqq8LyMzpWw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});